# For more information about the configurations used in this file, please
# see the Travis CI documentation: https://docs.travis-ci.com

language: python
dist: bionic
sudo: false
python:
- '3.8'

services:
  - docker

addons:
  apt:
    packages:
    - libgdal-dev
    - postgresql-11-postgis-2.5

env:
  global:
  - PGDATABASE=postgres
  - PGHOST=localhost
  - PGUSER=postgres
  - PGPASS=''
  - PGPORT=5432
  - POSTGRES_IMAGE=mdillon/postgis:11
  - DATABASE_URL=postgis://${PGUSER}:${PGPASS}@${PGHOST}:${PGPORT}/${PGDATABASE}

cache:
  pip: true

before_install:
  - sudo service postgresql stop
  - docker run --rm --name pg-docker -d -p ${PGPORT}:5432 --tmpfs /var/lib/postgresql/data:rw ${POSTGRES_IMAGE}
  - docker ps

install:
  - pip install -r requirement/development.txt
  - pip install flake8

script:
- flake8
- pytest --cov -v --tb=native


after_script:
- coveralls
- bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
