# Generated by Django 3.0.7 on 2020-06-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklisted_restaurant',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_restaurant', related_query_name='blacklisted_restaurant', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_restaurant',
            field=models.ManyToManyField(blank=True, related_name='favourite_restaurant', related_query_name='favourite_restaurant', to='restaurant.Restaurant'),
        ),
    ]
